plugin: gcp_compute
projects:
  - infra-244305
regions:
  - us-central1
groups:
  app: "'-app-' in name"
  db: "'-db-' in name"
hostnames:
#  - name
  - public_ip
#  - private_ip
compose:
# Set an inventory parameter to use the Public IP address to connect to the host
# For Private ip use "networkInterfaces[0].networkIP"
ansible_host: networkInterfaces[0].accessConfigs[0].natIP
filters: []
auth_kind: serviceaccount
service_account_file: /home/ivbor/.ansible/infra-244305-71e82336c304.json
