--- 
- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
  # Adding key to access the repository
  - name: Add APT key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com
      state: present

  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      filename: mongodb-org-3.2.list
      state: present

  - name: Update apt cache as a separate task
    apt:
      name: python-apt
      update_cache: true

  - name: pause playbook to unlock dpkg frontend lock-file
    pause:
      seconds: 15

  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present
      allow-unauthenticated: yes

  - name: Configure Mongod service
    systemd:
      name: mongod
      state: started
      enabled: yes
