---
- name: Install Ruby && Bundler
  hosts: all
  become: true
  tasks:
  # Install ruby and bundler dependencies in loop
  - name: Install ruby and rubygems and required packages
    apt: 
      name: {{ item }}
      state: present 
      update_cache: yes
    loop:
      - ruby-full
      - ruby-bundler
      - build-essential
